### PR TITLE
added AddMissingOverrideAnnotationRefactoring

### PR DESCRIPTION
**Pull request by Arnaud-Nauwynck**
I have added class "AddMissingOverrideAnnotationRefactoring"
(not in preferences, only in contextual menu)
code might be improved... for example to remove old-style javadoc comment /* see ...*/

### CODE REVIEW

**Comment by Fabrice-TIERCELIN** [comment]
There are problems in your PR. Travis raises check fails (see the "Details" link above). Firstly, your class needs a JavaDoc, and so on. I let you fix it and we will look at your code when it's OK.

Thanx for contributing and welcome :)

**Comment by Fabrice-TIERCELIN** [comment]
This feature already exists on Eclipse without plugin (Windows -> Preferences -> Java -> Editor -> Save Action -> Configure -> Missing Code -> Add missing annotations -> @override) so I think we will not add this PR. But we will keep this as your code is still interesting and can be used as an example.

**Comment by Arnaud-Nauwynck** [comment]
the "save action" can not be easily applied recursively to a list of files
.. this is why I added it in the plugin

Notice that I have other ideas/implementations of automated refactorings
that might be of interest for your plugin
(I have them in a plugin of mine, with the preview dialog, and easier to
program at the AST level  ... but not with a top level selection dialog of
rules to apply)
for example:
- a "lomboker" to remove getter and setter, and replace with @Getter,
@Setter
- a lomboker to replace explicit final local variable by lombok "val"
("var" is experimental in lombok, and full of bugs)   ...see
http://arnaud-nauwynck.github.io/2017/01/18/eclipse-lomboker.html
- add "final" to local variable that are effectively final
- concatenate C-style "declare then assign local variable"  (example:
"Object var = null;  \n var = new.." )
- replace function with several parameters, with function with 1 reguest
parameter class  ... for example to be Rest/Json compliant with
spring-webmvc or jax-rs
- many others..



2017-02-01 7:07 GMT+01:00 Fabrice TIERCELIN <notifications@github.com>:

**Comment by Fabrice-TIERCELIN** [comment]
I'm not worried about having new refactoring to code :) If you can't implement one, there are tons of others. There are lots of sonarlint to code, for example.

To apply the missing override to an entire project: right-click on the project -> Source -> Clean Up

**Pull request closed without merging**
