### PR TITLE
Implement refactoring of elimination of unnecessary Map.keySet calls.

### PR DESCRIPTION
**Pull request by gzsombor**
Several method on map.keySet() is just a delegate on the underlying map, which can be omitted : isEmpty, size, contains, remove, clear

### CODE REVIEW

**Comment by JnRouvignac** [comment]
Thanks for this PR!

I will try to review it shortly.

**Comment by JnRouvignac** [comment]
I am going to approve the PR and then do some cleanups myself.

**Comment by JnRouvignac** [comment]
Code cleanups done in commit aa43bbc01bfabe864877afde66b1a9c0c263c46f .

Thanks a lot for your contribution!

**Comment by gzsombor** [comment]
Thanks for the quick response - and merge :smile: 
Really appreciated !

**Comment by JnRouvignac** [comment]
You're welcome!
The rule is straightforward, so reviewing was quick.

By the way, I think the rule can be improved to also handle `Map.values()`. What do you think?

**Comment by gzsombor** [comment]
Good idea, I'm thinking about fixing the for loops over the keys, where the value is used : 
```
for (String key : map.keySet()) {
   Object value = map.get(key);

}
```

to something like : 
```
for (Map.Entry entry : map.entrySet()) {
   String key = entry.getKey();
   Object value = entry.getValue();

}
```

**Comment by JnRouvignac** [comment]
I thought about it too. 
That would be awesome.

**Comment by JnRouvignac** [comment]
I thought about it too.
That would be awesome.

**Pull request merged**
