### PR TITLE
Extract ASTHelper.isMethod to work with IMethodBinding objects 

### PR DESCRIPTION
**Pull request by luiscruz**
This is a replacement for the previous PR #217

### CODE REVIEW

**Comment by JnRouvignac** [comment]
Hi @luiscruz,

This PR does not pass the build.
You must run `mvn clean install` before submitting it.
It runs additional checks that all need to pass.

Cheers,
Jean-Noel

**Comment by luiscruz** [comment]
Alright, I'll fix it asap.

**Comment by JnRouvignac** [comment]
Don't worry.
It can wait until you have time to work on it again.

**Comment by JnRouvignac** [comment]
This PR's been merged already BTW

**Pull request merged**
