### PR TITLE
Refactoring to ensure that the logger is always  'private final static'

### PR DESCRIPTION
**Pull request by gzsombor**
This is not bulletproof refactoring, it could result in a compilation error, if the logger is used
 outside of the class, even in a child class - however changing the field to protected is fine.

I had to move the modifier manipulation code to the ASTHelper.

### CODE REVIEW

**Comment by Fabrice-TIERCELIN** [comment]
Hi, @gzsombor. Nice to see you again.

**Comment by gzsombor** [comment]
Hi @Fabrice-TIERCELIN, there are lot's of possible refactorings, which needs to be written, unfortunately there is so less time 😄

**Comment by gzsombor** [comment]
Is there any technical reason, why it's not merged ? Or just a lack of time 😄

**Comment by Fabrice-TIERCELIN** [comment]
Just a lack of boldness :) I will look at it.

**Comment by gzsombor** [comment]
I know it's hard, and even the tests are failing ... ;-)

**Comment by gzsombor** [comment]
Finally, I was able to fix the tests. Could you merge it? :)

**Comment by Fabrice-TIERCELIN** [comment]
Focus your efforts into other refactorings. There are lots of more prioritary refactorings to do like adding try/finally to close streams... I'm not sure we will pull this request.

**Comment by gzsombor** [comment]
Fine, it's your decision. Everyone prefers to fix his own bug, so am I :)

**Comment by Fabrice-TIERCELIN** [comment]
This feature is not universal enough. It should be built for personal use only.

**Pull request closed without merging**
